# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180917_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='title',
        ),
    ]
